# Schirmung von Leitern

- Flächiges Auflegen
  - Abschirmung sollte flächig aufgelegt werden.
    -> HF-Störungen werden besser unterdrückt

- Führung eines geschirmten Kabels 
  - Kabel sollte nicht quer durch den Raum gelegt werden.
  - Verlegen entlang metallischen Flächen mit Massepotential verringert das Störpotential.
  
## Einseitig vs. zweiseitig aufgelegen

- Kapazitive Störkopplung von außen 
  - Kapazitive Störkopplung führt zu Strömen in Schirm und Innenleiter. 
  - Wird durch beidseitiges auflegen teilweise kompensiert.

- Störspannung zwischen zwei Massepunkten
  - Bei einseitigem Auflegen wird eine Störspannung zwischen zwei Massepunkten direkt zum Nutzsignal addiert.
  - Beidseitiges Auflegen vermindert die Störung durch die Belastung des Schirms.

- Masseschleife
  - Beidseitiges Auflegen kann zu Masseschleifen führen. 
  - Magnetische Wechselfelder können in einer flächig aufgespannten Masseschleife (Erdschleife) einen Induktionsstrom bewirken. 
    -> Addiert aufs Nutzsignal
  - Mögliche Lösungen:
    - Einseitige Schirmung.
    - Gerätemassen nicht direkt auf Erde und die Schirme nur auf die Gerätemasse.
    - Symmetrische Signalleitungen (ggf. ohne Abschirmung).

- Antennenwirkung
  - Kabelschirm kann egal ob einseitig beidseitig Aufgelegt als Antenne wirken. 
  - Wirkungsrichtung einstrahlend und abstrahlend. 


## Materialien

- Abschirmgeflecht. 
  - hervorragende Leiter für HF.
  - Skin-Effekt wenig ausgeprägt.
  - Dichte bestimmt Abschirmung.

- Federstreifen und Gaskets.
  - Abschirmung für Messschrank. 
  - Können auf Kanten und Gehäuseöffnungen geklebt/geschraubt werden. 


