# Mögliche Lösungen {#solutions}

Die Messungen an unterschiedlichen Kabeln und Aufgbauten hat gezeigt, dass eine zusätzliche Abschirmung mit einem Kupfergeflecht, die Störfestigkeit der Kabel verbessert. 
Daher sollen im folgenden mehrere mögliche Umsetzungen verglichen werden.

## Kupfergeflecht

Die vorhandenen RG-58 Koaxialkabel könnten zusätzlich mit einem äußeren Kupfergeflecht umhüllt werden.

**Noch nichts genaueres. Michael Weigl ist informiert.**

## Andere Kabel

Eine weitere Möglichkeit wäre die Anschaffung neuer Kabel mit doppelter Isolierung. 
Gut geeignet wären die Kabel [RG-223](https://koaxshop.de/gx2/RG--Koaxkabel-50-Ohm/RG-223-Koaxkabel.html), [RG-142](https://koaxshop.de/gx2/RG--Koaxkabel-50-Ohm/RG-142-Koaxkabel.html) oder [RG-400](https://koaxshop.de/gx2/RG--Koaxkabel-50-Ohm/RG-400-Koaxkabel.html).
Diese haben ähnliche Maße wie unsere vorhandenen [RG-58](https://koaxshop.de/gx2/RG--Koaxkabel-50-Ohm/RG-58-Koaxkabel.html) Kabel, verfügen allerdings über ein zusätzliches versilbertes Kupfergeflecht zur besseren Schirmung.
Außerdem können sie auch mit BNC-Steckern versehen werden.

```{r}
cables <-
  tidyr::tibble(
    "Kabel" = c(
      "RG-58", 
      "RG-223",
      "RG-142",
      "RG-400"
    ),
    "Außendurchmesser" = c(
      "5.0 mm", 
      "5.2 mm",
      "4.95 mm",
      "4.95 mm"
    ),
    "Isolation" = c(
      "PE (Polyethylen)", 
      "PE (Polyethylen)",
      "PTFE (Teflon)",
      "PTFE (Teflon)"
    ),
    "Schirmung" =	c(
      "Kupfergeflecht verzinnt", 
      "Doppelt Cu Geflecht versilbert",
      "Doppelt Cu Geflecht versilbert",
      "Doppelt Cu Geflecht versilbert"
    ),
    "Innenleiter" = c(
      "19x0.2mm Kupfer-Litze verzinnt", 
      "1x0,9mm Kupfer versilbert",
      "1x0,95mm Kupfer versilbert",
      "19x0,2mm Kupferlitze versilbert"
      ),
    "Kapazität" = c(
      "101 pF/m",
      "101 pF/m",
      "96 pF/m",
      "96 pF/m"
    ),
    "Preis" = c(
      "0.75 EUR/m",
      "2.40 EUR/m",
      "6.75 EUR/m",
      "7.75 EUR/m"
    )
  )

cables |> 
  knitr::kable()
```

Alle vier Kabel besitzen einen minimalen Biegeradius von 30cm, sowie einen Wellenwiderstand von 50 Ohm +/- 2.
